name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python (if you're using Python to generate the site)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install any dependencies (skip this if you're not using Python)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Copy the built site from _build/html to docs/
      - name: Copy built site to docs/
        run: |
          mkdir -p docs
          cp -r Documentation/_build/html/* docs/

      # Configure Git for pushing to GitHub Pages
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Commit and push the changes
      - name: Commit and push changes
        run: |
          git add docs
          git commit -m "Deploy to GitHub Pages"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
